### ISSUE TITLE
Error: Too many workers. Max. 16 allowed workers.

### ISSUE THREAD

**Issue by deniro21** [altcha-org/altcha#36]
Hi! I have "Error: Too many workers. Max. 16 allowed workers.". Everything works well, but this error is displayed in the console every time I verify. What does it mean? I've tried different browsers, but the error persists.

**Comment by ovx** [comment]
Hi, and thanks for reporting. The widget didn't properly handle navigator.hardwareConcurrency provided by your browser but it still verified because it falls back to non-worker verification. Its fixed in version 0.4.3.

**Comment by deniro21** [comment]
I installed the new version, but the problem still exists...

**Comment by ovx** [comment]
Hi, if you rely on the automatically provided number of workers, this version 0.4.3 should work without errors.

Some things you can try to troubleshoot:
- if you're using `workers=""` widget attribute, make sure the number is between 1...16 
- make sure that you're actually loading the correct version and not a cached older version. You can enable debug by adding `debug` attribute to the widget and you'll see the widget version in the developer console logs
- if that doesn't help, post your HTML widget code here including the value of `navigator.hardwareConcurrency` (paste it to the developer console)

**Comment by deniro21** [comment]
The new version works, thanks! I just forgot to remove the workers attribute :)
